// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laufxrudadcgjvpcbull.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhdWZ4cnVkYWRjZ2p2cGNidWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDM3NDYsImV4cCI6MjA3MDc3OTc0Nn0.BCLiKctZzLSV6twCx6uLjnXmq6LdY8Qdl8vYMRnkNyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});